/** Reviewed static statement registry. Identifiers are never supplied by callers or interpolated at runtime. */
export const INSERTS = {
  'brain.llm_cache': {
    columns: ['prompt_id', 'prompt_version', 'model_id', 'input_hash', 'response'],
    pk: ['prompt_id', 'prompt_version', 'model_id', 'input_hash'], mode: 'nothing',
    sql: 'INSERT INTO brain.llm_cache (prompt_id, prompt_version, model_id, input_hash, response) VALUES ($1, $2, $3, $4, $5::jsonb) ON CONFLICT DO NOTHING',
  },
"brain.case_run": { columns: ["id","question","principal_id","intent","status","rules_version","prompt_versions","model_ids","evidence_snapshot_ids","reference_snapshot_ids","started_at","finished_at","created_at"], pk: ["id"], mode: "update", sql: "INSERT INTO brain.case_run (id, question, principal_id, intent, status, rules_version, prompt_versions, model_ids, evidence_snapshot_ids, reference_snapshot_ids, started_at, finished_at, created_at) VALUES ($1, $2, $3, $4::jsonb, $5, $6, $7::jsonb, $8::jsonb, $9, $10, $11, $12, $13) ON CONFLICT (id) DO UPDATE SET question = EXCLUDED.question, principal_id = EXCLUDED.principal_id, intent = EXCLUDED.intent, status = EXCLUDED.status, rules_version = EXCLUDED.rules_version, prompt_versions = EXCLUDED.prompt_versions, model_ids = EXCLUDED.model_ids, evidence_snapshot_ids = EXCLUDED.evidence_snapshot_ids, reference_snapshot_ids = EXCLUDED.reference_snapshot_ids, started_at = EXCLUDED.started_at, finished_at = EXCLUDED.finished_at, created_at = EXCLUDED.created_at" },
"brain.fact": { columns: ["id","run_id","claim_key","subject","attribute","scope","slot_id","status","confidence","winner_claim_id","winning_value","reasons","needs_verification","impact","reference_only","created_at"], pk: ["id"], mode: "update", sql: "INSERT INTO brain.fact (id, run_id, claim_key, subject, attribute, scope, slot_id, status, confidence, winner_claim_id, winning_value, reasons, needs_verification, impact, reference_only, created_at) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7, $8, $9, $10, $11, $12::jsonb, $13, $14, $15, $16) ON CONFLICT (id) DO UPDATE SET run_id = EXCLUDED.run_id, claim_key = EXCLUDED.claim_key, subject = EXCLUDED.subject, attribute = EXCLUDED.attribute, scope = EXCLUDED.scope, slot_id = EXCLUDED.slot_id, status = EXCLUDED.status, confidence = EXCLUDED.confidence, winner_claim_id = EXCLUDED.winner_claim_id, winning_value = EXCLUDED.winning_value, reasons = EXCLUDED.reasons, needs_verification = EXCLUDED.needs_verification, impact = EXCLUDED.impact, reference_only = EXCLUDED.reference_only, created_at = EXCLUDED.created_at" },
"brain.gap": { columns: ["id","run_id","type","slot_id","fact_id","description","closed_by","status","created_at"], pk: ["id"], mode: "update", sql: "INSERT INTO brain.gap (id, run_id, type, slot_id, fact_id, description, closed_by, status, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT (id) DO UPDATE SET run_id = EXCLUDED.run_id, type = EXCLUDED.type, slot_id = EXCLUDED.slot_id, fact_id = EXCLUDED.fact_id, description = EXCLUDED.description, closed_by = EXCLUDED.closed_by, status = EXCLUDED.status, created_at = EXCLUDED.created_at" },
"brain.conflict": { columns: ["id","run_id","fact_id","type","severity","claim_ids","resolution","resolved_by","status","created_at"], pk: ["id"], mode: "update", sql: "INSERT INTO brain.conflict (id, run_id, fact_id, type, severity, claim_ids, resolution, resolved_by, status, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) ON CONFLICT (id) DO UPDATE SET run_id = EXCLUDED.run_id, fact_id = EXCLUDED.fact_id, type = EXCLUDED.type, severity = EXCLUDED.severity, claim_ids = EXCLUDED.claim_ids, resolution = EXCLUDED.resolution, resolved_by = EXCLUDED.resolved_by, status = EXCLUDED.status, created_at = EXCLUDED.created_at" },
"brain.canonical": { columns: ["key","value","fact_id","run_id","confidence","verified_tier","next_review_at","created_at"], pk: ["key"], mode: "update", sql: "INSERT INTO brain.canonical (key, value, fact_id, run_id, confidence, verified_tier, next_review_at, created_at) VALUES ($1, $2::jsonb, $3, $4, $5, $6, $7, $8) ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, fact_id = EXCLUDED.fact_id, run_id = EXCLUDED.run_id, confidence = EXCLUDED.confidence, verified_tier = EXCLUDED.verified_tier, next_review_at = EXCLUDED.next_review_at, created_at = EXCLUDED.created_at" },
"brain.attribution": { columns: ["run_id","source_kind","source_id","contribution_pct","accepted_claims","rejected_claims","reliability_pct"], pk: ["run_id","source_kind","source_id"], mode: "update", sql: "INSERT INTO brain.attribution (run_id, source_kind, source_id, contribution_pct, accepted_claims, rejected_claims, reliability_pct) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7) ON CONFLICT (run_id, source_kind, source_id) DO UPDATE SET contribution_pct = EXCLUDED.contribution_pct, accepted_claims = EXCLUDED.accepted_claims, rejected_claims = EXCLUDED.rejected_claims, reliability_pct = EXCLUDED.reliability_pct" },
"brain.org_event": { columns: ["id","type","scope","domain","effective_at","created_at"], pk: ["id"], mode: "update", sql: "INSERT INTO brain.org_event (id, type, scope, domain, effective_at, created_at) VALUES ($1, $2, $3::jsonb, $4, $5, $6) ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, scope = EXCLUDED.scope, domain = EXCLUDED.domain, effective_at = EXCLUDED.effective_at, created_at = EXCLUDED.created_at" },
"brain.run_stage": { columns: ["run_id","stage","status","started_at","finished_at","stats","error"], pk: ["run_id","stage"], mode: "update", sql: "INSERT INTO brain.run_stage (run_id, stage, status, started_at, finished_at, stats, error) VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7) ON CONFLICT (run_id, stage) DO UPDATE SET status = EXCLUDED.status, started_at = EXCLUDED.started_at, finished_at = EXCLUDED.finished_at, stats = EXCLUDED.stats, error = EXCLUDED.error" },
"brain.claim_group": { columns: ["run_id","claim_id","source_kind","source_id","group_id"], pk: ["run_id","claim_id"], mode: "update", sql: "INSERT INTO brain.claim_group (run_id, claim_id, source_kind, source_id, group_id) VALUES ($1, $2, $3, $4, $5) ON CONFLICT (run_id, claim_id) DO UPDATE SET source_kind = EXCLUDED.source_kind, source_id = EXCLUDED.source_id, group_id = EXCLUDED.group_id" },
"brain.claim_score": { columns: ["run_id","claim_id","source_kind","source_id","fact_id","role","code","score","breakdown","reasons"], pk: ["run_id","claim_id"], mode: "update", sql: "INSERT INTO brain.claim_score (run_id, claim_id, source_kind, source_id, fact_id, role, code, score, breakdown, reasons) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::jsonb, $10::jsonb) ON CONFLICT (run_id, claim_id) DO UPDATE SET source_kind = EXCLUDED.source_kind, source_id = EXCLUDED.source_id, fact_id = EXCLUDED.fact_id, role = EXCLUDED.role, code = EXCLUDED.code, score = EXCLUDED.score, breakdown = EXCLUDED.breakdown, reasons = EXCLUDED.reasons" },
"brain.fact_decision": { columns: ["run_id","fact_id","rules_version","fired","decided_by","cap","correction_for","escalate_to","scope_fit","independent_corroborations"], pk: ["run_id","fact_id"], mode: "update", sql: "INSERT INTO brain.fact_decision (run_id, fact_id, rules_version, fired, decided_by, cap, correction_for, escalate_to, scope_fit, independent_corroborations) VALUES ($1, $2, $3, $4::jsonb, $5, $6, $7, $8, $9, $10) ON CONFLICT (run_id, fact_id) DO UPDATE SET rules_version = EXCLUDED.rules_version, fired = EXCLUDED.fired, decided_by = EXCLUDED.decided_by, cap = EXCLUDED.cap, correction_for = EXCLUDED.correction_for, escalate_to = EXCLUDED.escalate_to, scope_fit = EXCLUDED.scope_fit, independent_corroborations = EXCLUDED.independent_corroborations" },
"brain.edge": { columns: ["id","type","from_id","from_kind","to_id","to_kind","props","run_id"], pk: ["id"], mode: "update", sql: "INSERT INTO brain.edge (id, type, from_id, from_kind, to_id, to_kind, props, run_id) VALUES ($1, $2, $3, $4, $5, $6, $7::jsonb, $8) ON CONFLICT (id) DO UPDATE SET type = EXCLUDED.type, from_id = EXCLUDED.from_id, from_kind = EXCLUDED.from_kind, to_id = EXCLUDED.to_id, to_kind = EXCLUDED.to_kind, props = EXCLUDED.props, run_id = EXCLUDED.run_id" },
"evidence.document": { columns: ["id","source_system","source_uri","title","owner_id","author_id","last_edited_at","last_verified_at","verified_tier","valid_until","declared_scope","allowed_principals","created_at"], pk: ["id"], mode: "update", sql: "INSERT INTO evidence.document (id, source_system, source_uri, title, owner_id, author_id, last_edited_at, last_verified_at, verified_tier, valid_until, declared_scope, allowed_principals, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11::jsonb, $12, $13) ON CONFLICT (id) DO UPDATE SET source_system = EXCLUDED.source_system, source_uri = EXCLUDED.source_uri, title = EXCLUDED.title, owner_id = EXCLUDED.owner_id, author_id = EXCLUDED.author_id, last_edited_at = EXCLUDED.last_edited_at, last_verified_at = EXCLUDED.last_verified_at, verified_tier = EXCLUDED.verified_tier, valid_until = EXCLUDED.valid_until, declared_scope = EXCLUDED.declared_scope, allowed_principals = EXCLUDED.allowed_principals, created_at = EXCLUDED.created_at" },
"evidence.snapshot": { columns: ["id","document_id","content_hash","text","fetched_at","version","created_at"], pk: ["id"], mode: "nothing", sql: "INSERT INTO evidence.snapshot (id, document_id, content_hash, text, fetched_at, version, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7) ON CONFLICT DO NOTHING" },
"evidence.passage": { columns: ["id","snapshot_id","ordinal","start_off","end_off","text","embedding","created_at"], pk: ["id"], mode: "nothing", sql: "INSERT INTO evidence.passage (id, snapshot_id, ordinal, start_off, end_off, text, embedding, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7::vector, $8) ON CONFLICT DO NOTHING" },
"evidence.claim": { columns: ["id","source_id","snapshot_id","passage_id","span_start","span_end","quote","subject","attribute","value","qualifiers","temporal","polarity","modality","extraction_confidence","claim_key","created_at"], pk: ["id"], mode: "update", sql: "INSERT INTO evidence.claim (id, source_id, snapshot_id, passage_id, span_start, span_end, quote, subject, attribute, value, qualifiers, temporal, polarity, modality, extraction_confidence, claim_key, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10::jsonb, $11::jsonb, $12::jsonb, $13, $14, $15, $16, $17) ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, snapshot_id = EXCLUDED.snapshot_id, passage_id = EXCLUDED.passage_id, span_start = EXCLUDED.span_start, span_end = EXCLUDED.span_end, quote = EXCLUDED.quote, subject = EXCLUDED.subject, attribute = EXCLUDED.attribute, value = EXCLUDED.value, qualifiers = EXCLUDED.qualifiers, temporal = EXCLUDED.temporal, polarity = EXCLUDED.polarity, modality = EXCLUDED.modality, extraction_confidence = EXCLUDED.extraction_confidence, claim_key = EXCLUDED.claim_key, created_at = EXCLUDED.created_at" },
"org.person": { columns: ["id","name","email","team","country","active","principal_ids","created_at"], pk: ["id"], mode: "update", sql: "INSERT INTO org.person (id, name, email, team, country, active, principal_ids, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, email = EXCLUDED.email, team = EXCLUDED.team, country = EXCLUDED.country, active = EXCLUDED.active, principal_ids = EXCLUDED.principal_ids, created_at = EXCLUDED.created_at" },
"org.expertise": { columns: ["person_id","subject","country","weight"], pk: ["person_id","subject","country"], mode: "update", sql: "INSERT INTO org.expertise (person_id, subject, country, weight) VALUES ($1, $2, $3, $4) ON CONFLICT (person_id, subject, country) DO UPDATE SET weight = EXCLUDED.weight" },
"reference.wiki_page": { columns: ["id","space","title","uri","owner_id","official","last_edited_at","last_verified_at","declared_scope","allowed_principals","out_links","created_at"], pk: ["id"], mode: "update", sql: "INSERT INTO reference.wiki_page (id, space, title, uri, owner_id, official, last_edited_at, last_verified_at, declared_scope, allowed_principals, out_links, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9::jsonb, $10, $11, $12) ON CONFLICT (id) DO UPDATE SET space = EXCLUDED.space, title = EXCLUDED.title, uri = EXCLUDED.uri, owner_id = EXCLUDED.owner_id, official = EXCLUDED.official, last_edited_at = EXCLUDED.last_edited_at, last_verified_at = EXCLUDED.last_verified_at, declared_scope = EXCLUDED.declared_scope, allowed_principals = EXCLUDED.allowed_principals, out_links = EXCLUDED.out_links, created_at = EXCLUDED.created_at" },
"reference.wiki_snapshot": { columns: ["id","page_id","content_hash","text","fetched_at","created_at"], pk: ["id"], mode: "nothing", sql: "INSERT INTO reference.wiki_snapshot (id, page_id, content_hash, text, fetched_at, created_at) VALUES ($1, $2, $3, $4, $5, $6) ON CONFLICT DO NOTHING" },
"reference.wiki_section": { columns: ["id","snapshot_id","ordinal","heading_path","start_off","end_off","text","embedding","created_at"], pk: ["id"], mode: "nothing", sql: "INSERT INTO reference.wiki_section (id, snapshot_id, ordinal, heading_path, start_off, end_off, text, embedding, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8::vector, $9) ON CONFLICT DO NOTHING" },
"reference.reference_fact": { columns: ["id","source_id","snapshot_id","passage_id","span_start","span_end","quote","subject","attribute","value","qualifiers","temporal","polarity","modality","extraction_confidence","claim_key","created_at"], pk: ["id"], mode: "update", sql: "INSERT INTO reference.reference_fact (id, source_id, snapshot_id, passage_id, span_start, span_end, quote, subject, attribute, value, qualifiers, temporal, polarity, modality, extraction_confidence, claim_key, created_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10::jsonb, $11::jsonb, $12::jsonb, $13, $14, $15, $16, $17) ON CONFLICT (id) DO UPDATE SET source_id = EXCLUDED.source_id, snapshot_id = EXCLUDED.snapshot_id, passage_id = EXCLUDED.passage_id, span_start = EXCLUDED.span_start, span_end = EXCLUDED.span_end, quote = EXCLUDED.quote, subject = EXCLUDED.subject, attribute = EXCLUDED.attribute, value = EXCLUDED.value, qualifiers = EXCLUDED.qualifiers, temporal = EXCLUDED.temporal, polarity = EXCLUDED.polarity, modality = EXCLUDED.modality, extraction_confidence = EXCLUDED.extraction_confidence, claim_key = EXCLUDED.claim_key, created_at = EXCLUDED.created_at" },
} as const;

export const COUNTS = {
"brain.case_run": "SELECT count(*) AS n FROM brain.case_run",
"brain.fact": "SELECT count(*) AS n FROM brain.fact",
"brain.gap": "SELECT count(*) AS n FROM brain.gap",
"brain.conflict": "SELECT count(*) AS n FROM brain.conflict",
"brain.canonical": "SELECT count(*) AS n FROM brain.canonical",
"brain.attribution": "SELECT count(*) AS n FROM brain.attribution",
"brain.org_event": "SELECT count(*) AS n FROM brain.org_event",
"brain.run_stage": "SELECT count(*) AS n FROM brain.run_stage",
"brain.claim_group": "SELECT count(*) AS n FROM brain.claim_group",
"brain.claim_score": "SELECT count(*) AS n FROM brain.claim_score",
"brain.fact_decision": "SELECT count(*) AS n FROM brain.fact_decision",
"brain.edge": "SELECT count(*) AS n FROM brain.edge",
"evidence.document": "SELECT count(*) AS n FROM evidence.document",
"evidence.snapshot": "SELECT count(*) AS n FROM evidence.snapshot",
"evidence.passage": "SELECT count(*) AS n FROM evidence.passage",
"evidence.claim": "SELECT count(*) AS n FROM evidence.claim",
"org.person": "SELECT count(*) AS n FROM org.person",
"org.expertise": "SELECT count(*) AS n FROM org.expertise",
"reference.wiki_page": "SELECT count(*) AS n FROM reference.wiki_page",
"reference.wiki_snapshot": "SELECT count(*) AS n FROM reference.wiki_snapshot",
"reference.wiki_section": "SELECT count(*) AS n FROM reference.wiki_section",
"reference.reference_fact": "SELECT count(*) AS n FROM reference.reference_fact",
"brain.verification_request": "SELECT count(*) AS n FROM brain.verification_request",
"brain.verification_event": "SELECT count(*) AS n FROM brain.verification_event",
"brain.llm_cache": "SELECT count(*) AS n FROM brain.llm_cache",
"brain.resource_usage": "SELECT count(*) AS n FROM brain.resource_usage",
} as const;

// TypeScript readonly declarations also have runtime enforcement.
for (const statement of Object.values(INSERTS)) {
  Object.freeze(statement.columns);
  Object.freeze(statement.pk);
  Object.freeze(statement);
}
Object.freeze(INSERTS);
Object.freeze(COUNTS);
